// Code generated by Arduino IoT Cloud, DO NOT EDIT.

#include <ArduinoIoTCloud.h>
#include <Arduino_ConnectionHandler.h>


const char THING_ID[] = "aa9b7bf5-1d5a-49e6-b3cf-49497f6e0310";

const char SSID[]     = 'Shadesmar'; //SECRET_SSID;Network SSID (name)
const char PASS[]     = 'Zigge2000'; //SECRET_PASS; Network password (use for WPA, or use as key for WEP)


CloudTemperature temperature;

void initProperties(){

  ArduinoCloud.setThingId(THING_ID);
  ArduinoCloud.addProperty(temperature, READ, 60 * SECONDS, NULL);

}

WiFiConnectionHandler ArduinoIoTPreferredConnection(SSID, PASS);
